name: Deploy Container

on:
  push:
    tags:
      - "*@*.*.*"
permissions:
  contents: write
  packages: write
  id-token: write
  pull-requests: write

env:
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
  AUTH_URL: ${{ secrets.AUTH_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 8
      - name: Login to GitHub Container Registry

        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}
      - name: get the tag and set is as the image version
        id: vars
        run: |
          TAG=${GITHUB_REF#refs/*/}
          TAG=${TAG#*@} # This line extracts the part after the '@' symbol
          echo ::set-output name=tag::$TAG
          echo $TAG
          echo "
            AUTH_SECRET=${AUTH_SECRET}
            AUTH_URL=${AUTH_URL}
              " >.env
      - name: Build and push
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }} .
          docker push ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }}
      - name: create a release 
        uses: softprops/action-gh-release@v2.0.4
        if: startsWith(github.ref, 'refs/tags/')
       